"""
POST /deploy/pagedin — deploy to the PagedIn owner GitHub account.
POST /deploy/self    — deploy to the user's own GitHub account.
GET  /auth/github    — exchange OAuth code for token.
"""
import logging
from fastapi import APIRouter, HTTPException
from fastapi.responses import JSONResponse
from pydantic import BaseModel
from services.github_service import deploy_as_owner, deploy_as_user, exchange_code_for_token
from utils.security import verify_deploy_token

logger = logging.getLogger(__name__)
router = APIRouter()


class PagedinDeployRequest(BaseModel):
    html: str
    deploy_token: str
    parsed_name: str = "resume"
    honeypot: str = ""


class SelfDeployRequest(BaseModel):
    html: str
    github_token: str
    first_name: str = "my"
    honeypot: str = ""


class OAuthCallbackRequest(BaseModel):
    code: str


@router.post("/deploy/pagedin")
async def deploy_pagedin(body: PagedinDeployRequest):
    """
    Deploy the generated site using the PagedIn owner GitHub account.
    Requires a valid signed deploy_token issued by /generate.
    """
    # Honeypot
    if body.honeypot:
        logger.warning("HONEYPOT_TRIGGERED path=/deploy/pagedin")
        return JSONResponse(content={"url": "https://pagedin.app"})

    # Validate the deploy token — ensures HTML was generated by our backend
    is_valid, error_msg = verify_deploy_token(body.deploy_token, body.html)
    if not is_valid:
        logger.warning(f"Invalid deploy token: {error_msg}")
        raise HTTPException(
            status_code=403,
            detail=f"Deploy authorization failed: {error_msg}"
        )

    try:
        url = await deploy_as_owner(body.html, body.parsed_name)
        return JSONResponse(content={"url": url})
    except RuntimeError as e:
        logger.error(f"Owner deploy error: {e}")
        raise HTTPException(status_code=502, detail=str(e))
    except Exception as e:
        logger.error(f"Unexpected deploy error: {e}")
        raise HTTPException(
            status_code=500,
            detail="Deployment failed. Please try again in a moment."
        )


@router.post("/deploy/self")
async def deploy_self(body: SelfDeployRequest):
    """
    Deploy the generated site to the user's own GitHub account.
    Requires the user's GitHub OAuth access token.
    """
    # Honeypot
    if body.honeypot:
        logger.warning("HONEYPOT_TRIGGERED path=/deploy/self")
        return JSONResponse(content={"url": "https://github.com"})

    if not body.github_token:
        raise HTTPException(
            status_code=400,
            detail="GitHub access token is required for self-deployment."
        )

    if not body.html:
        raise HTTPException(status_code=400, detail="HTML content is required.")

    try:
        url = await deploy_as_user(body.html, body.github_token, body.first_name)
        return JSONResponse(content={"url": url})
    except RuntimeError as e:
        logger.error(f"Self deploy error: {e}")
        raise HTTPException(status_code=502, detail=str(e))
    except Exception as e:
        logger.error(f"Unexpected self deploy error: {e}")
        raise HTTPException(
            status_code=500,
            detail="Deployment failed. Please try again."
        )


@router.post("/auth/github")
async def github_oauth_callback(body: OAuthCallbackRequest):
    """
    Exchange a GitHub OAuth authorization code for an access token.
    The token is returned to the frontend and stored in memory only.
    """
    if not body.code:
        raise HTTPException(status_code=400, detail="Authorization code is required.")

    try:
        token = await exchange_code_for_token(body.code)
        return JSONResponse(content={"access_token": token})
    except RuntimeError as e:
        logger.error(f"GitHub OAuth error: {e}")
        raise HTTPException(status_code=400, detail=str(e))
